# NVIM
alias vim="nvim"

# Paths
source ~/.profile

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh-histfile
HISTSIZE=1000
SAVEHIST=1000
HIST_STAMPS='dd.mm.yyyy'
setopt autocd

# Keys mapping
set -o vi
bindkey -v
bindkey "^L" clear-screen
bindkey "^R" history-incremental-search-backward
bindkey "" backward-kill-word # <C-BS>
bindkey -M viins 'jk' vi-cmd-mode
bindkey "^[[1;5D" backward-word # <C-Left>
bindkey "^[[1;5C" forward-word # <C-Right>

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/thiago/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi


source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk
# Auto Suggestions
zinit light zsh-users/zsh-autosuggestions
bindkey '^ ' autosuggest-accept

# Zinit Plugins
zinit light spaceship-prompt/spaceship-prompt


# pnpm
export PNPM_HOME="/home/thiago/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# Go path
export PATH="$PATH:/usr/local/go/bin"
